# microservice-dev.yml
server:
  port: 999

custom:
  message: "Ciao, questo è l'ambiente di prod!"
  featureX-enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username: prod_user
    password: prod_password
